//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPhoto
    {
        public int idPhoto { get; set; }
        public int idMaster { get; set; }
        public byte[] PhotoBinary { get; set; }
        public byte[] PhotoPath { get; set; }
    
        public virtual TableMaster TableMaster { get; set; }
    }
}
