//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableApplication()
        {
            this.TableRepairApp = new HashSet<TableRepairApp>();
        }
    
        public int idApplication { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Fatherland { get; set; }
        public int idBrand { get; set; }
        public int idMaster { get; set; }
        public int idRepair { get; set; }
        public string Photo { get; set; }
    
        public virtual TableBrand TableBrand { get; set; }
        public virtual TableMaster TableMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableRepairApp> TableRepairApp { get; set; }
    }
}
