//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRepairApp
    {
        public int idRepairApp { get; set; }
        public int idRepair { get; set; }
        public int idApplication { get; set; }
    
        public virtual TableApplication TableApplication { get; set; }
        public virtual TableRepair TableRepair { get; set; }
    }
}
