//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableClient()
        {
            this.TableApplication = new HashSet<TableApplication>();
            this.TableAuto = new HashSet<TableAuto>();
        }
    
        public int idClient { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Fatherland { get; set; }
        public System.DateTime Birthday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableApplication> TableApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableAuto> TableAuto { get; set; }
    }
}
