//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableAuto
    {
        public int idAuto { get; set; }
        public int idClient { get; set; }
        public int idBrand { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual TableBrand TableBrand { get; set; }
        public virtual TableClient TableClient { get; set; }
    }
}
